@BASE_URL = http://localhost:3000/api
@ACCESS_TOKEN = {{login.response.body.token}}

### Login
# @name login
POST {{BASE_URL}}/auth/login HTTP/1.1
content-type: application/json

{
 "email" : "milk@gmail.com",
 "password" : "11111111"
}

###  Create auction
POST  {{BASE_URL}}/auctions
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
  "productId": 155,
  "startTime": "2026-04-29T04:56:13.000Z",
  "endTime": "2026-04-29T05:17:13.000Z",
  "startingPrice": 1,
  "reservePrice": 100,
  "minIncrement": 100,
  "status": "WAITING"
}

###  get all auctions
GET  {{BASE_URL}}/auctions
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}  

###  get popular auctions
GET  {{BASE_URL}}/auctions/popular?limit=5
content-type: application/json

###  get auction by id
GET  {{BASE_URL}}/auctions/64
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}  

###  get auction by product id
GET  {{BASE_URL}}/auctions/product/133
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}  

###  DELETE auction by id
DELETE  {{BASE_URL}}/auctions/77
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}  

###  Update auction
PATCH  {{BASE_URL}}/auctions/39
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}  

{
  "endTime": "2026-05-20T08:35:29.000Z"
}

# {
#   "startTime": "2026-06-06T06:13:00.000Z",
#   "endTime": "2026-05-20T08:35:29.000Z",
#   "startingPrice": 1000,
#   "reservePrice": 100,
#   "minIncrement": 200,
#   "status": "WAITING"
# }