@BASE_URL = http://localhost:3000/api
@ACCESS_TOKEN = {{login.response.body.token}}

### Login
# @name login
POST {{BASE_URL}}/auth/login HTTP/1.1
content-type: application/json

{
 "email" : "fruity5@gmail.com",
 "password" : "loml555"
}

###  Create auction
POST  {{BASE_URL}}/auctions
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
  "productId": 121,
  "startTime": "2026-04-27T04:20:22.000Z",
  "endTime": "2026-04-27T04:30:22.000Z",
  "startingPrice": 100,
  "reservePrice": 15000,
  "minIncrement": 100,
  "status": "WAITING"
}

###  get all auctions
GET  {{BASE_URL}}/auctions
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}  

###  get auction by id
GET  {{BASE_URL}}/auctions/5
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}  

###  get auction by product id
GET  {{BASE_URL}}/auctions/product/56
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}  

###  DELETE auction by id
DELETE  {{BASE_URL}}/auctions/10
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}  

###  Update auction
PATCH  {{BASE_URL}}/auctions/10
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}  

{
  "startTime": "2026-06-06T06:13:00.000Z",
  "endTime": "2026-06-09T06:13:00.000Z",
  "startingPrice": 1000,
  "reservePrice": 5500,
  "minIncrement": 200,
  "status": "WAITING"
}