@BASE_URL = http://localhost:3000/api
@ACCESS_TOKEN = {{login.response.body.token}}

### Login
# @name login
POST {{BASE_URL}}/auth/login HTTP/1.1
content-type: application/json

{
 "email" : "tingchan@gmail.com",
 "password" : "11111111"
}

###  Create bid
POST  {{BASE_URL}}/bids
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}} 

{
  "bidderId": 20,
  "auctionId": 36, 
  "amount": 6000
}

###  get all bids
GET  {{BASE_URL}}/bids
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}} 

###  get bid by id
GET  {{BASE_URL}}/bids/cmo2quvvz0000muyzswdp4eh3
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}} 

###  get bids by user id
GET  {{BASE_URL}}/bids/user/99
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}} 

###  DELETE bid by id
DELETE  {{BASE_URL}}/bids/cmo2rh5x80002z8yz6i9zo4u2
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}} 

###  Update bid status
PATCH  {{BASE_URL}}/bids/cmo6t436j0000enyzn106ulhi
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}} 

{
    "isWinning": true
} 
