@BASE_URL = http://localhost:3000/api
### Login
POST {{BASE_URL}}/auth/login 
content-type: application/json

{
 "identity" : "tanacom0249@hotmail.com",
 "password" : "Jammy@1223_3432"
}

###  Create bid
POST  {{BASE_URL}}/bids
content-type: application/json
Authorization: Bearer 

{
  "bidderId": 1000,
  "auctionId": 5, 
  "amount": 2000
}

###  get all bids
GET  {{BASE_URL}}/bids
content-type: application/json
Authorization: Bearer 

###  get bid by id
GET  {{BASE_URL}}/bids/cmo2quvvz0000muyzswdp4eh3
content-type: application/json
Authorization: Bearer 

###  DELETE bid by id
DELETE  {{BASE_URL}}/bids/cmo2r3yls0001muyzlgxs5mke
content-type: application/json
Authorization: Bearer 

###  Update bid status
POST  {{BASE_URL}}/bids
content-type: application/json
Authorization: Bearer 

{
    "isWinning": true
} 
