@BASE_URL = http://localhost:3000/api
### Login
POST {{BASE_URL}}/auth/login 
content-type: application/json

{
 "identity" : "tanacom0249@hotmail.com",
 "password" : "Jammy@1223_3432"
}

###  Create product
POST  {{BASE_URL}}/products
content-type: application/json
Authorization: Bearer 

{
   "name": "Garmin xo", 
   "description": "excellent dive computer with geolocation tagging", 
   "categoryId": 2, 
   "sellerId": 8
}

###  Get all products
GET  {{BASE_URL}}/products
content-type: application/json
Authorization: Bearer 

###  Get all categories
GET  {{BASE_URL}}/products/categories
content-type: application/json
Authorization: Bearer 