@BASE_URL = http://localhost:3000/api
@ACCESS_TOKEN = {{login.response.body.token}}

### Login
# @name login
POST {{BASE_URL}}/auth/login HTTP/1.1
content-type: application/json

{
 "email" : "tester22@gmail.com",
 "password" : "88889999"
}

###  Create product
POST  {{BASE_URL}}/products
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
   "name": "Hollerix", 
   "description": "best designer watch", 
   "categoryId": 1
}


###  Update product data
PATCH  {{BASE_URL}}/products/104
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}} 

{
   "name": "Hollerix 3", 
   "description": "the ultimate designer watch", 
   "categoryId": 2
}

###  Get product by id
GET  {{BASE_URL}}/products/56
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}} 

###  Get all products
GET  {{BASE_URL}}/products
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}} 


###  Delete product by Id
DELETE  {{BASE_URL}}/products/78
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}} 

###  Get all categories
GET  {{BASE_URL}}/products/categories
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}} 