@BASE_URL = http://localhost:3000/api
### Login
POST {{BASE_URL}}/auth/login 
content-type: application/json

{
 "identity" : "tanacom0249@hotmail.com",
 "password" : "Jammy@1223_3432"
}

###  Create product
POST  {{BASE_URL}}/products
content-type: application/json
Authorization: Bearer 

{
   "name": "Hollerix", 
   "description": "best designer watch", 
   "categoryId": 1
}


###  Update product data
PATCH  {{BASE_URL}}/products/103
content-type: application/json
Authorization: Bearer 

{
   "name": "Hollerix 2", 
   "description": "the best designer watch", 
   "categoryId": 2
}

###  Get product by id
GET  {{BASE_URL}}/products/103
content-type: application/json
Authorization: Bearer 

###  Get all products
GET  {{BASE_URL}}/products
content-type: application/json
Authorization: Bearer 


###  Delete product by Id
DELETE  {{BASE_URL}}/products/77
content-type: application/json
Authorization: Bearer 

###  Get all categories
GET  {{BASE_URL}}/products/categories
content-type: application/json
Authorization: Bearer 