@BASE_URL = http://localhost:3000/api
@ACCESS_TOKEN = {{login.response.body.token}}

### Login
# @name login
POST {{BASE_URL}}/auth/login HTTP/1.1
content-type: application/json

{
 "email" : "fruity5@gmail.com",
 "password" : "loml555"
}

###  Get all users
GET  {{BASE_URL}}/users
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

###  Get user by id
GET  {{BASE_URL}}/users/208
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

###  Update user by id
PATCH  {{BASE_URL}}/users/208
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{ 
   "username": "provocation2",
  "email": "tester224@gmail.com",  
  "firstname": "hello", 
  "lastname": "kitty", 
  "phone": "23512335"  
}

###  DELETE user by id
DELETE   {{BASE_URL}}/users/207
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

###  Update user by id
PATCH  {{BASE_URL}}/users/208/addresses/29
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{ 
  "label": "SCHOOL",   
  "street": "Wannasorn building",    
  "city":    "Bangkok",   
  "state": "BKK city",     
  "postalCode": "01400",
  "country": "Bangkok",    
  "isDefault": false
}